{{- if .Values.nginx.enabled }}
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: {{ template "rasa-x.nginx.standard-conf" . }}
  labels:
    {{ include "rasa-x.labels" . | nindent 4 }}
{{- end }}

data:
  nginx.conf: {{ tpl (.Files.Get "nginx-config-files/nginx.conf") . | quote }}
  ssl.conf.template: {{ tpl (.Files.Get "nginx-config-files/ssl.conf.template") . | quote }}
  rasax.nginx.template: {{ tpl (.Files.Get "nginx-config-files/rasax.nginx.template") . | quote }}
  entrypoint.sh: {{ tpl (.Files.Get "nginx-config-files/entrypoint.sh") . | quote }}


