{{- if .Values.nginx.enabled }}
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    {{- include "rasa-x.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  progressDeadlineSeconds: {{ .Values.global.progressDeadlineSeconds }}
  replicas: {{ default 1 .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      {{- include "rasa-x.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: nginx
  template:
    metadata:
      labels:
        {{- include "rasa-x.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: nginx
    spec:
      automountServiceAccountToken: false
      {{ include "rasa-x.spec" . }}
      {{- if .Values.nginx.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nginx.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.nginx.tolerations }}
      tolerations:
{{ toYaml .Values.nginx.tolerations | indent 6 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.nginx.name }}:{{ .Values.nginx.tag | default (include "rasa-x.version" .) }}"
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        {{- if .Values.nginx.command }}
        command:
          {{- toYaml .Values.nginx.command | nindent 10 }}
        {{- end }}
        {{- if .Values.nginx.args }}
        args:
          {{- toYaml .Values.nginx.args | nindent 10 }}
        {{- end }}
        ports:
        - name: "http"
          containerPort: 8080
          protocol: "TCP"
        livenessProbe:
          exec:
            command:
            - curl
            - localhost:8080/nginx_status
          initialDelaySeconds: {{ .Values.nginx.initialProbeDelay }}
          failureThreshold: 10
        readinessProbe:
          exec:
            command:
            - curl
            - localhost:8080/nginx_status
          initialDelaySeconds: {{ .Values.nginx.initialProbeDelay }}
        env:
        - name: "RASA_X_HOST"
          value: "{{ include "rasa-x.host" . }}:{{ .Values.rasax.port }}"
        - name: "RASA_PRODUCTION_HOST"
          value: "{{ include "rasa-x.fullname" . }}-{{ .Values.rasa.versions.rasaProduction.serviceName }}:{{ .Values.rasa.port }}"
        - name: "CUSTOM_ACTION_HOST"
          value: "{{ include "rasa-x.fullname" . }}-app:{{ template "rasa-x.custom-actions.port" . }}"
        volumeMounts:
{{- if .Values.nginx.extraVolumeMounts }}
{{ toYaml .Values.nginx.extraVolumeMounts | indent 8 }}
{{- end }}
        - mountPath: "/opt/bitnami/nginx/conf/bitnami/terms"
          name: "agreement"
        {{ if .Values.nginx.certificateSecret }}
        - name: "certificates"
          readOnly: true
          mountPath: "/opt/bitnami/certs"
        {{ end }}
        {{- with .Values.nginx.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
{{- if .Values.nginx.extraVolumes }}
{{ toYaml .Values.nginx.extraVolumes | indent 6 }}
{{- end }}
      - configMap:
          items:
          - key: "agree"
            path: "agree.txt"
          name: {{ template "rasa-x.nginx.agreement" . }}
        name: "agreement"
      {{ if .Values.nginx.certificateSecret }}
      - name: "certificates"
        secret:
          secretName: {{ .Values.nginx.certificateSecret }}
      {{ end }}
{{- end }}
