{{- if and .Values.ingress.enabled (not .Values.nginx.enabled) -}}
{{- $fullName := include "rasa-x.fullname" . -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-rasa-open-source
  labels:
    {{- include "rasa-x.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.ingress.annotationsRasa }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host | quote }}
    {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
    http:
      paths:
      - backend:
          service:
            name: {{ $fullName }}-{{ $.Values.rasa.versions.rasaProduction.serviceName }}
            port: 
              number: {{ $.Values.rasa.port }}
        path: /core/(.*)
        pathType: Prefix
      - backend:
          service:
            name: {{ $fullName }}-{{ $.Values.rasa.versions.rasaProduction.serviceName }}
            port: 
              number: {{ $.Values.rasa.port }}
        path: /webhooks/
        pathType: Prefix
      - backend:
          service:
            name: {{ $fullName }}-{{ $.Values.rasa.versions.rasaProduction.serviceName }}
            port: 
              number: {{ $.Values.rasa.port }}
        path: /socket.io
        pathType: Exact
    {{- else -}}
    http:
      paths:
      - backend:
          serviceName: {{ $fullName }}-{{ $.Values.rasa.versions.rasaProduction.serviceName }}
          servicePort: {{ $.Values.rasa.port }}
        path: /core/(.*)
      - backend:
          serviceName: {{ $fullName }}-{{ $.Values.rasa.versions.rasaProduction.serviceName }}
          servicePort: {{ $.Values.rasa.port }}
        path: /webhooks/
      - backend:
          serviceName: {{ $fullName }}-app
          servicePort: {{ default 5055 $.Values.app.port }}
        path: /app/(.*)
      - backend:
          serviceName: {{ $fullName }}-{{ $.Values.rasa.versions.rasaProduction.serviceName }}
          servicePort: {{ $.Values.rasa.port }}
        path: /socket.io
    {{- end }}  
  {{- end }}
{{- end }}
