apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ include "rasa-x.host" . }}
  labels:
    {{ include "rasa-x.labels" . | nindent 4 }}
    app.kubernetes.io/component: rasa-x
spec:
  ports:
  - port: {{ .Values.rasax.port }}
    targetPort: http
    protocol: "TCP"
    name: "http"
  selector:
    {{- include "rasa-x.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: rasa-x
