name: Changelog
# When a new tag pushed
# - Generate changelogs from formatted commit messages
# - Update the latest release body with generated changelogs
on:
  push:
    tags:
    - '*'

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Generate Changelog
      uses: scottbrenner/generate-changelog-action@73f136c18da43958251923577e831d643fa24d4a # 1.3.1
      id: changelog
      env:
        REPO: ${{ github.repository }}

    - name: Update Release body
      # check if there is changelog
      if: startsWith(steps.changelog.outputs.changelog, '####')
      run: |
        # Get release id
        RELEASE_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq '.id')

        RELEASE_BODY="${{ steps.changelog.outputs.changelog }}"
        RELEASE_BODY="${RELEASE_BODY//$'\n'/'\n'}"

        # Update release body
        curl -X PATCH -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/releases/${RELEASE_ID}" \
          -d "{\"body\":\"$RELEASE_BODY\"}"
